FROM node:20-bullseye

# Labels
LABEL org.opencontainers.image.authors="justxwayz"
LABEL org.opencontainers.image.source="https://github.com/justxwayz/VirtualizationToContainerization"
LABEL org.opencontainers.image.vendor="justxwayz / MyLibrary"

WORKDIR /app

COPY package.json .

RUN npm install && npm cache clean --force

COPY ./src ./src

# app User
RUN useradd -m mylibrary
RUN chown -R mylibrary:mylibrary /app
USER mylibrary

ENV PORT=3000
EXPOSE 3000

CMD ["npm", "run", "dev"]
